camel:
  springboot:
    # The Camel context name
    name: CamelRestClient
    main-run-controller: true

# Binding health checks to a different port
# change actuator endpoints path
management:
  server:
    port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 2s
  processOrderPeriod: 5s
  
